# Generated by Django 4.1.5 on 2023-02-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_delete_order_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dastavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('count', models.PositiveBigIntegerField(blank=True, default=1, null=True)),
                ('price', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('yetkazib_berilgan', 'Yetkazib berilgan'), ('tayyorlanyapdi', 'Tayyorlanyapdi')], default='tayyorlanyapdi', max_length=255)),
            ],
            options={
                'verbose_name': 'Dastavka',
                'verbose_name_plural': 'Dastavka',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
